version: '3.8'
services:
  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000"
    networks:
      - app-network

  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - fastapi

networks:
  app-network:
    driver: bridge